site_name: Manual QA docs
theme: github
docs_dir: docs
use_directory_urls: false

nav:
  - Home: index.md
  - HTTP: 
      - Введение в HTTP: http/http.md
      - Заголовки HTTP (Headers): http/http-headers.md
      - Методы HTTP (Methods): http/http_methods/main.md
      - HTTP-статусы: 
          - Общее о кодах состояния: http/http_status/main.md
          - 1xx — Информационные: http/http_status/http-status-100.md
          - 2xx — Успех:: http/http_status/http-status-200.md
          - 3xx — Перенаправления: http/http_status/http-status-300.md
          - 4xx — Ошибки клиента: http/http_status/http-status-400.md
          - 5xx — Ошибки сервера: http/http_status/http-status-500.md
  - Основы работы с API:
      - Введение в API: api/api-intro.md
      - Типы API: api/api-types.md
      - Форматы данных: api/data-formats.md
  - Практика работы с API:
      - Как делать запросы в API: api/api-practice.md
      - Структура запроса в API: api/api-structure.md
      - Параметры запроса в API: api/api-params.md
  - Валидация и тестирование:
      - Как проверять ответы API: api/api-tests.md
      - Типичные ошибки в API и как их находить: api/api-errors.md
      - Автоматизация тестирования: api/api-practice.md
  - Полезные инструменты и советы:
      - Документация API в OpenAPI/Swagger: api/openapi.md
      - Работа с ошибками: api/api-errors.md
  - Примеры реальных сценариев:
      - Регистрация пользователя: api/api-registration.md
      - Авторизация и получение токена: api/api-auth.md
      - Создание, изменение, удаление данных через API: api/api-crud.md
      - Получение списка с фильтрацией и пагинацией: api/api-pagination.md
  - Безопасность:
      - Введение в авторизацию: security/auth-intro.md
      - Что такое токены: security/tokens.md
      - Basic Auth: security/basic-auth.md
      - Bearer Token / JWT: security/jwt.md
      - OAuth 2.0: security/oauth2.md
  - Безопасность (расширение):
      - CSRF: security/csrf.md
      - SSL/TLS и HTTPS: security/ssl-tls.md
